name: 'CI tests'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            bats -t tests/